//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNotification
    {
        public int NotificationId { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string ExtraColum { get; set; }
    }
}
